import 'package:flutter/material.dart';

class LanguageManager extends ChangeNotifier {
  static final LanguageManager instance = LanguageManager._internal();
  LanguageManager._internal();

  String _currentLanguage = 'English'; 

  String get currentLanguage => _currentLanguage;

  void changeLanguage(String newLanguage) {
    if (_currentLanguage != newLanguage) {
      _currentLanguage = newLanguage;
      notifyListeners();
    }
  }

  final Map<String, Map<String, String>> _translations = {
    'Hindi': <String, String>{
      '''Super Administrator''': '''हिं: Super Administrator''',
      '''Ecstasy School 1''': '''Ecstasy स्कूल 1''',
      '''Ecstasy School 2''': '''Ecstasy स्कूल 2''',
      '''Ecstasy School 3''': '''Ecstasy स्कूल 3''',
      '''Logout''': '''लॉगआउट''',
      '''Students Overview''': '''हिं: Students Overview''',
      '''Students List''': '''छात्र सूची''',
      '''Register New Student''': '''छात्र पंजीकरण''',
      '''Student Promotions''': '''छात्र पदోन्नति''',
      '''Student Siblings''': '''छात्र भाई-बहन''',
      '''Student ID Cards''': '''छात्र आईडी कार्ड''',
      '''Teachers List''': '''शिक्षक सूची''',
      '''Add New Teacher''': '''नया शिक्षक जोड़ें''',
      '''Configuration''': '''विन्यास''',
      '''Examination''': '''परीक्षा''',
      '''Communications''': '''संचार''',
      '''System Updates''': '''सिस्टम अपडेट''',
      '''Video Tutorials''': '''वीडियो ट्यूटोरियल''',
      '''About Us''': '''हमारे बारे में''',
      '''Empowering Education,\nInspiring Futures''': '''हिं: Empowering Education,\nInspiring Futures''',
      '''At Ecstasy School, we are committed to providing quality education through innovation, technology and a student-first approach.''': '''At Ecstasy स्कूल, we are committed to providing quality education through innovation, technology and a छात्र-first approach.''',
      '''Our Mission''': '''हिं: Our Mission''',
      '''To deliver a world-class education that nurtures curiosity, builds character and empowers every student to achieve their full potential.''': '''To deliver a world-कक्षा education that nurtures curiosity, builds character and empowers every छात्र to achieve their full potential.''',
      '''Our Vision''': '''हिं: Our Vision''',
      '''To be a global leader in education, recognized for academic excellence, innovation and the holistic development of students.''': '''हिं: To be a global leader in education, recognized for academic excellence, innovation and the holistic development of students.''',
      '''Our Core Values''': '''हिं: Our Core Values''',
      '''Learn More''': '''Learn अधिक''',
      '''Leadership Team''': '''हिं: Leadership Team''',
      '''View All''': '''सभी देखें''',
      '''in''': '''हिं: in''',
      '''Our History''': '''हिं: Our History''',
      '''Read More''': '''Read अधिक''',
      '''“''': '''हिं: “''',
      '''Education is the most powerful weapon which you can use to change the world.''': '''हिं: Education is the most powerful weapon which you can use to change the world.''',
      '''— Nelson Mandela''': '''हिं: — Nelson Mandela''',
      '''Get in Touch''': '''हिं: Get in Touch''',
      '''Cancel''': '''रद्द करें''',
      '''Delete Academic Year''': '''हटाएं Academic Year''',
      '''Delete''': '''हटाएं''',
      '''Academic Years''': '''हिं: Academic Years''',
      '''Add New''': '''जोड़ें New''',
      '''Academic Year''': '''हिं: Academic Year''',
      '''Is Active''': '''हिं: Is Active''',
      '''Items per page:''': '''हिं: Items per page:''',
      '''25''': '''हिं: 25''',
      '''Current Academic Year''': '''हिं: Current Academic Year''',
      '''Save''': '''सहेजें''',
      '''Delete Entry''': '''हटाएं Entry''',
      '''Entry deleted''': '''हिं: Entry deleted''',
      '''10''': '''हिं: 10''',
      '''Attendance Analysis''': '''उपस्थिति Analysis''',
      '''Present''': '''उपस्थित''',
      '''Delete Branch''': '''हटाएं Branch''',
      '''Are you sure you want to delete this branch?''': '''Are you sure you want to हटाएं this branch?''',
      '''Branch List''': '''हिं: Branch List''',
      '''Code''': '''हिं: Code''',
      '''Name & Head''': '''हिं: Name & Head''',
      '''Contact''': '''हिं: Contact''',
      '''No branches found''': '''हिं: No branches found''',
      '''Certificate Previews''': '''हिं: Certificate Previews''',
      '''ECSTASY INTERNATIONAL SCHOOL''': '''ECSTASY INTERNATIONAL स्कूल''',
      '''DATE OF ISSUE''': '''हिं: DATE OF ISSUE''',
      '''Certificates Overview''': '''हिं: Certificates Overview''',
      '''2,568''': '''हिं: 2,568''',
      '''Total''': '''कुल''',
      '''Issued Certificates Log''': '''हिं: Issued Certificates Log''',
      '''Starting new chat...''': '''हिं: Starting new chat...''',
      '''Start New Chat''': '''हिं: Start New Chat''',
      '''Select a chat''': '''हिं: Select a chat''',
      '''Delete Mapping''': '''हटाएं Mapping''',
      '''Are you sure?''': '''हिं: Are you sure?''',
      '''Class Subjects Mapping''': '''कक्षा Subjects Mapping''',
      '''Class  /  Subject  /  Teacher''': '''कक्षा  /  Subject  /  शिक्षक''',
      '''No mappings added yet.''': '''हिं: No mappings added yet.''',
      '''Message Detail''': '''हिं: Message Detail''',
      '''Sent''': '''हिं: Sent''',
      '''Reply''': '''हिं: Reply''',
      '''Forward''': '''हिं: Forward''',
      '''Update''': '''अपडेट करें''',
      '''Are you sure you want to remove this configuration entry?''': '''हिं: Are you sure you want to remove this configuration entry?''',
      '''Entry deleted.''': '''हिं: Entry deleted.''',
      '''Create Event''': '''हिं: Create Event''',
      '''Add New Event''': '''जोड़ें New Event''',
      '''Event added successfully!''': '''हिं: Event added successfully!''',
      '''Save Event''': '''सहेजें Event''',
      '''Events Calendar''': '''हिं: Events Calendar''',
      '''Jun 2026''': '''हिं: Jun 2026''',
      '''Upcoming Events''': '''हिं: Upcoming Events''',
      '''View All Upcoming Events >''': '''सभी देखें Upcoming Events >''',
      '''All Events''': '''हिं: All Events''',
      '''Exam Schedule''': '''हिं: Exam Schedule''',
      '''View Calendar''': '''हिं: View Calendar''',
      '''Performance Overview''': '''हिं: Performance Overview''',
      '''75%''': '''हिं: 75%''',
      '''Avg Pass''': '''हिं: Avg Pass''',
      '''Student Exam Performance Logs''': '''छात्र Exam Performance Logs''',
      '''Fee Type Collection Breakdown''': '''शुल्क Type Collection Breakdown''',
      '''Recent Transactions''': '''हिं: Recent Transactions''',
      '''Branch''': '''हिं: Branch''',
      '''Ecstasy School 1 (ECS001)''': '''Ecstasy स्कूल 1 (ECS001)''',
      '''Ecstasy School 2 (ECS002)''': '''Ecstasy स्कूल 2 (ECS002)''',
      '''Ecstasy School 3 (ECS003)''': '''Ecstasy स्कूल 3 (ECS003)''',
      '''Tuition Fee Collection''': '''Tuition शुल्क Collection''',
      '''Transport Fee Collection''': '''Transport शुल्क Collection''',
      '''Fee Due Students''': '''शुल्क Due Students''',
      '''Term 1''': '''हिं: Term 1''',
      '''Term 2''': '''हिं: Term 2''',
      '''Term 3''': '''हिं: Term 3''',
      '''School Fee Structures (Annual)''': '''स्कूल शुल्क Structures (Annual)''',
      '''School''': '''स्कूल''',
      '''Tuition''': '''हिं: Tuition''',
      '''Transport''': '''हिं: Transport''',
      '''Exam''': '''हिं: Exam''',
      '''Please select at least one student to generate invoices.''': '''Please select at least one छात्र to generate invoices.''',
      '''Term 1 Invoice Batch''': '''हिं: Term 1 Invoice Batch''',
      '''Generate Selected''': '''हिं: Generate Selected''',
      '''Select All Students''': '''हिं: Select All Students''',
      '''All students have generated invoices!''': '''हिं: All students have generated invoices!''',
      '''Get Fee Details''': '''Get शुल्क Details''',
      '''Year''': '''हिं: Year''',
      '''Class''': '''कक्षा''',
      '''Fee Type''': '''शुल्क Type''',
      '''Amount''': '''हिं: Amount''',
      '''Delete Fee Type''': '''हटाएं शुल्क Type''',
      '''Fee type deleted''': '''शुल्क type deleted''',
      '''Student Fee Types''': '''छात्र शुल्क Types''',
      '''No fee types added yet.''': '''No शुल्क types added yet.''',
      '''Are you sure you want to delete this entry?''': '''Are you sure you want to हटाएं this entry?''',
      '''Popular Help Topics''': '''हिं: Popular Help Topics''',
      '''Frequently Asked Questions''': '''हिं: Frequently Asked Questions''',
      '''My Support Tickets''': '''हिं: My Support Tickets''',
      '''Delete Holiday''': '''हटाएं Holiday''',
      '''Holiday deleted''': '''हिं: Holiday deleted''',
      '''Holidays List''': '''हिं: Holidays List''',
      '''Date''': '''हिं: Date''',
      '''Description''': '''हिं: Description''',
      '''No holidays added yet.''': '''हिं: No holidays added yet.''',
      '''Room Status Overview''': '''हिं: Room Status Overview''',
      '''120''': '''हिं: 120''',
      '''Total Rooms''': '''कुल Rooms''',
      '''Hostel Blocks Breakdown''': '''हिं: Hostel Blocks Breakdown''',
      '''Hostel Residents Log''': '''हिं: Hostel Residents Log''',
      '''ID Card Previews''': '''हिं: ID Card Previews''',
      '''Principal Sign''': '''हिं: Principal Sign''',
      '''ID Cards Summary''': '''हिं: ID Cards Summary''',
      '''1,245''': '''हिं: 1,245''',
      '''Recent ID Card Logs''': '''हिं: Recent ID Card Logs''',
      '''Would you like to add a new image from gallery or remove the existing one?''': '''Would you like to जोड़ें a new image from gallery or remove the existing one?''',
      '''Image removed successfully!''': '''हिं: Image removed successfully!''',
      '''Remove Image''': '''हिं: Remove Image''',
      '''Image added successfully!''': '''हिं: Image added successfully!''',
      '''Add/Update Image''': '''जोड़ें/अपडेट करें Image''',
      '''Fee Configurations Requiring Attention''': '''शुल्क Configurations Requiring Attention''',
      '''The following records have inconsistencies that prevent accurate invoice generation and billing cycles. Please audit and resolve them.''': '''हिं: The following records have inconsistencies that prevent accurate invoice generation and billing cycles. Please audit and resolve them.''',
      '''Fix & Reconcile''': '''हिं: Fix & Reconcile''',
      '''Total Reconciliation Engine''': '''कुल Reconciliation Engine''',
      '''Reported Total''': '''Reported कुल''',
      '''Calculated Total''': '''Calculated कुल''',
      '''Discrepancy''': '''हिं: Discrepancy''',
      '''Audit Explanation:''': '''हिं: Audit Explanation:''',
      '''Resolve Adjustment''': '''हिं: Resolve Adjustment''',
      '''DATA DISCREPANCIES''': '''हिं: DATA DISCREPANCIES''',
      '''Add Book''': '''जोड़ें Book''',
      '''Issued Date''': '''हिं: Issued Date''',
      '''Due Date''': '''हिं: Due Date''',
      '''Send Reminder''': '''हिं: Send Reminder''',
      '''Category Distribution''': '''हिं: Category Distribution''',
      '''Reports Analytics''': '''हिं: Reports Analytics''',
      '''1,256''': '''हिं: 1,256''',
      '''Popular Reports Templates''': '''हिं: Popular Reports Templates''',
      '''Recent Generated Reports''': '''हिं: Recent Generated Reports''',
      '''Export Data''': '''हिं: Export Data''',
      '''Close''': '''हिं: Close''',
      '''Super Admin Settings''': '''Super प्रशासक सेटिंग्स''',
      '''Please select at least one class first.''': '''Please select at least one कक्षा first.''',
      '''Select Students''': '''हिं: Select Students''',
      '''Select All''': '''हिं: Select All''',
      '''Clear All''': '''हिं: Clear All''',
      '''Apply Selection''': '''हिं: Apply Selection''',
      '''Please select at least one class.''': '''Please select at least one कक्षा.''',
      '''Please select at least one pending term.''': '''हिं: Please select at least one pending term.''',
      '''No students are currently selected to receive SMS.''': '''हिं: No students are currently selected to receive SMS.''',
      '''Confirm Send SMS''': '''हिं: Confirm Send SMS''',
      '''You are about to send fee due SMS alerts to:''': '''You are about to send शुल्क due SMS alerts to:''',
      '''This action will dispatch automated SMS alerts to the parents of all selected students.''': '''हिं: This action will dispatch automated SMS alerts to the parents of all selected students.''',
      '''Send SMS''': '''हिं: Send SMS''',
      '''Sending SMS notifications...''': '''हिं: Sending SMS notifications...''',
      '''Success''': '''हिं: Success''',
      '''OK''': '''हिं: OK''',
      '''Send Fee Due SMS to Selected Students''': '''Send शुल्क Due SMS to Selected Students''',
      '''Fee pending from''': '''शुल्क pending from''',
      '''Send to All Students''': '''हिं: Send to All Students''',
      '''System Status''': '''हिं: System Status''',
      '''All Systems Operational''': '''हिं: All Systems Operational''',
      '''Recent Updates Log''': '''हिं: Recent Updates Log''',
      '''New Route''': '''हिं: New Route''',
      '''Manage Fleet''': '''हिं: Manage Fleet''',
      '''Track and manage your school buses in real time.''': '''Track and manage your स्कूल buses in real time.''',
      '''Active Fleet & Route Status''': '''हिं: Active Fleet & Route Status''',
      '''Assigned Driver''': '''हिं: Assigned Driver''',
      '''Stops Covered''': '''हिं: Stops Covered''',
      '''Seat Occupancy''': '''हिं: Seat Occupancy''',
      '''Experience''': '''हिं: Experience''',
      '''Assigned''': '''हिं: Assigned''',
      '''Safety Rating''': '''हिं: Safety Rating''',
      '''Featured Tutorials''': '''हिं: Featured Tutorials''',
      '''Add Branch''': '''जोड़ें Branch''',
      '''Add New Branch''': '''जोड़ें New Branch''',
      '''Please enter branch name''': '''हिं: Please enter branch name''',
      '''Save Branch''': '''सहेजें Branch''',
      '''Quick Actions''': '''हिं: Quick Actions''',
      '''Customize''': '''हिं: Customize''',
      '''Customize Quick Actions''': '''हिं: Customize Quick Actions''',
      '''Drag to reorder the icons below.''': '''हिं: Drag to reorder the icons below.''',
      '''Attendance Overview''': '''उपस्थिति Overview''',
      '''View attendance report''': '''View उपस्थिति report''',
      '''Recent Notices''': '''हिं: Recent Notices''',
      '''Fee Collection Overview''': '''शुल्क Collection Overview''',
      '''₹ (Lakh)''': '''हिं: ₹ (Lakh)''',
      '''CAMERA VIEWFINDER ACTIVE''': '''हिं: CAMERA VIEWFINDER ACTIVE''',
      '''Focus locked. Tap shutter to capture.''': '''हिं: Focus locked. Tap shutter to capture.''',
      '''Choose Profile Picture Source''': '''हिं: Choose Profile Picture Source''',
      '''Take Photo (Physical Camera)''': '''हिं: Take Photo (Physical Camera)''',
      '''Choose from Gallery''': '''हिं: Choose from Gallery''',
      '''Simulate Camera Viewfinder''': '''हिं: Simulate Camera Viewfinder''',
      '''Interactive mock camera capture''': '''हिं: Interactive mock camera capture''',
      '''Remove Photo''': '''हिं: Remove Photo''',
      '''Edit Admin Details''': '''संपादित करें प्रशासक Details''',
      '''Save Details''': '''सहेजें Details''',
      '''Account Information''': '''हिं: Account Information''',
      '''Security''': '''हिं: Security''',
      '''Preferences''': '''हिं: Preferences''',
      '''Admin Modules''': '''प्रशासक Modules''',
      '''Edit''': '''संपादित करें''',
      '''Two-Factor Authentication''': '''हिं: Two-Factor Authentication''',
      '''Add an extra layer of security''': '''जोड़ें an extra layer of security''',
      '''Change Password''': '''हिं: Change Password''',
      '''Active Sessions''': '''हिं: Active Sessions''',
      '''iPhone 13 (Current)''': '''हिं: iPhone 13 (Current)''',
      '''Active now''': '''हिं: Active now''',
      '''MacBook Pro''': '''हिं: MacBook Pro''',
      '''Last active: 2 hours ago''': '''हिं: Last active: 2 hours ago''',
      '''Notification Settings''': '''Notification सेटिंग्स''',
      '''Push Notifications''': '''हिं: Push Notifications''',
      '''Email Alerts''': '''हिं: Email Alerts''',
      '''SMS Updates''': '''हिं: SMS Updates''',
      '''Select Theme''': '''हिं: Select Theme''',
      '''System Default''': '''हिं: System Default''',
      '''Light Theme''': '''हिं: Light Theme''',
      '''Dark Theme''': '''हिं: Dark Theme''',
      '''Region & Time Zone''': '''हिं: Region & Time Zone''',
      '''Asia/Kolkata (IST)''': '''हिं: Asia/Kolkata (IST)''',
      '''America/New_York (EST)''': '''हिं: America/New_York (EST)''',
      '''Europe/London (GMT)''': '''हिं: Europe/London (GMT)''',
      '''Sign out from your account''': '''हिं: Sign out from your account''',
      '''Are you sure you want to logout?''': '''Are you sure you want to लॉगआउट?''',
      '''Add Student''': '''जोड़ें छात्र''',
      '''More Filters''': '''अधिक Filters''',
      '''Classes Overview (13)''': '''हिं: Classes Overview (13)''',
      '''No students found in this class.''': '''No students found in this कक्षा.''',
      '''Add New Student''': '''जोड़ें New छात्र''',
      '''Gender''': '''हिं: Gender''',
      '''Male''': '''हिं: Male''',
      '''Female''': '''हिं: Female''',
      '''Please enter student name''': '''Please enter छात्र name''',
      '''Save Student''': '''सहेजें छात्र''',
      '''No teachers found''': '''हिं: No teachers found''',
      '''Add Teacher''': '''जोड़ें शिक्षक''',
      '''Teacher Profile''': '''शिक्षक Profile''',
      '''Please enter teacher name''': '''Please enter शिक्षक name''',
      '''Please enter subject''': '''हिं: Please enter subject''',
      '''Save Teacher''': '''सहेजें शिक्षक''',
      '''Support Mails''': '''हिं: Support Mails''',
      '''12 unread queries''': '''हिं: 12 unread queries''',
      '''Active Chats''': '''हिं: Active Chats''',
      '''5 unread messages''': '''हिं: 5 unread messages''',
      '''Payments Received''': '''हिं: Payments Received''',
      '''3 recent transactions''': '''हिं: 3 recent transactions''',
      '''Leave Requests''': '''अवकाश Requests''',
      '''2 pending approvals''': '''हिं: 2 pending approvals''',
      '''5''': '''हिं: 5''',
      '''Hi, Need any help?''': '''हिं: Hi, Need any help?''',
      '''AI Assistant''': '''हिं: AI Assistant''',
      '''Powered by DeepMind''': '''हिं: Powered by DeepMind''',
      '''Simulation Mode Active''': '''हिं: Simulation Mode Active''',
      '''Password Recovery''': '''हिं: Password Recovery''',
      '''Enter your registered email or mobile number to receive a reset link.''': '''हिं: Enter your registered email or mobile number to receive a reset link.''',
      '''Recovery link sent successfully!''': '''हिं: Recovery link sent successfully!''',
      '''Send Link''': '''हिं: Send Link''',
      '''Choose an account''': '''हिं: Choose an account''',
      '''to continue to Ecstasy School ERP''': '''to continue to Ecstasy स्कूल ERP''',
      '''A''': '''हिं: A''',
      '''admin@ecstasy.edu''': '''प्रशासक@ecstasy.edu''',
      '''Admin Account''': '''प्रशासक Account''',
      '''S''': '''हिं: S''',
      '''student@ecstasy.edu''': '''छात्र@ecstasy.edu''',
      '''Student Account''': '''छात्र Account''',
      '''T''': '''हिं: T''',
      '''teacher@ecstasy.edu''': '''शिक्षक@ecstasy.edu''',
      '''Teacher Account''': '''शिक्षक Account''',
      '''Smart School Management''': '''Smart स्कूल Management''',
      '''Welcome Back!''': '''हिं: Welcome Back!''',
      '''Login to your account''': '''लॉगिन to your account''',
      '''User ID''': '''हिं: User ID''',
      '''Forgot Password?''': '''हिं: Forgot Password?''',
      '''OR''': '''हिं: OR''',
      '''Login with Google''': '''लॉगिन with Google''',
      '''Powered by''': '''हिं: Powered by''',
      '''ECSTASY''': '''हिं: ECSTASY''',
      '''SCHOOLS ERP''': '''हिं: SCHOOLS ERP''',
      '''© 2024 Ecstasy Schools ERP. All rights reserved.''': '''हिं: © 2024 Ecstasy Schools ERP. All rights reserved.''',
      '''No events scheduled for this day.''': '''हिं: No events scheduled for this day.''',
      '''Downloading Holiday Calendar...''': '''हिं: Downloading Holiday Calendar...''',
      '''Download''': '''हिं: Download''',
      '''Holiday Name''': '''हिं: Holiday Name''',
      '''Day''': '''हिं: Day''',
      '''Wednesday, 17 Jun 2026''': '''हिं: Wednesday, 17 Jun 2026''',
      '''Timetable''': '''हिं: Timetable''',
      '''View Full Timetable''': '''हिं: View Full Timetable''',
      '''Period''': '''हिं: Period''',
      '''Time''': '''हिं: Time''',
      '''Subject''': '''हिं: Subject''',
      '''Teacher''': '''शिक्षक''',
      '''Room''': '''हिं: Room''',
      '''Solve exercise questions from chapter 5.''': '''हिं: Solve exercise questions from chapter 5.''',
      '''Pending''': '''हिं: Pending''',
      '''Completed''': '''हिं: Completed''',
      '''Assignments''': '''हिं: Assignments''',
      '''Due Today – Submit before deadline!''': '''हिं: Due Today – Submit before deadline!''',
      '''Attendance''': '''उपस्थिति''',
      '''Attendance Summary''': '''उपस्थिति Summary''',
      '''Minimum required: 75% | You are above the requirement ✓''': '''हिं: Minimum required: 75% | You are above the requirement ✓''',
      '''Monthly Overview''': '''हिं: Monthly Overview''',
      '''Subject-wise Attendance''': '''Subject-wise उपस्थिति''',
      '''June 2026''': '''हिं: June 2026''',
      '''Recent History''': '''हिं: Recent History''',
      '''Diary''': '''हिं: Diary''',
      '''Full Timetable''': '''हिं: Full Timetable''',
      '''Break Time''': '''हिं: Break Time''',
      '''My Class''': '''My कक्षा''',
      '''Examination Overview''': '''हिं: Examination Overview''',
      '''Upcoming Exams''': '''हिं: Upcoming Exams''',
      '''View Timetable''': '''हिं: View Timetable''',
      '''Recent Exam Results''': '''हिं: Recent Exam Results''',
      '''View All Results''': '''सभी देखें Results''',
      '''Performance Analysis''': '''हिं: Performance Analysis''',
      '''Here is your academic overview based on recent exams:''': '''हिं: Here is your academic overview based on recent exams:''',
      '''Great job! Your performance has improved by 4% compared to the last term.''': '''हिं: Great job! Your performance has improved by 4% compared to the last term.''',
      '''Term 1 Exam Schedule''': '''हिं: Term 1 Exam Schedule''',
      '''Mid Term Academic Report''': '''हिं: Mid Term Academic Report''',
      '''Exam Name''': '''हिं: Exam Name''',
      '''Duration''': '''हिं: Duration''',
      '''Syllabus''': '''हिं: Syllabus''',
      '''View All Upcoming Exams''': '''सभी देखें Upcoming Exams''',
      '''Marks Obtained''': '''हिं: Marks Obtained''',
      '''Total Marks''': '''कुल Marks''',
      '''Percentage''': '''हिं: Percentage''',
      '''Grade''': '''हिं: Grade''',
      '''Preparing Hall Ticket...''': '''हिं: Preparing Hall Ticket...''',
      '''Hall Ticket downloaded successfully!''': '''हिं: Hall Ticket downloaded successfully!''',
      '''This tab is under development.''': '''हिं: This tab is under development.''',
      '''Total Annual Fees''': '''कुल Annual Fees''',
      '''₹ 45,000''': '''हिं: ₹ 45,000''',
      '''Fee Status''': '''शुल्क Status''',
      '''Downloading Fee Statement...''': '''Downloading शुल्क Statement...''',
      '''Download Statement''': '''हिं: Download Statement''',
      '''Particulars''': '''हिं: Particulars''',
      '''Amount (₹)''': '''हिं: Amount (₹)''',
      '''Status''': '''हिं: Status''',
      '''Total Paid''': '''कुल Paid''',
      '''₹ 20,000''': '''हिं: ₹ 20,000''',
      '''Total Due''': '''कुल Due''',
      '''₹ 25,000''': '''हिं: ₹ 25,000''',
      '''Redirecting to payment gateway...''': '''हिं: Redirecting to payment gateway...''',
      '''Pay Now''': '''हिं: Pay Now''',
      '''Paid''': '''हिं: Paid''',
      '''Unpaid''': '''हिं: Unpaid''',
      '''Recent Payments''': '''हिं: Recent Payments''',
      '''Important Notes''': '''हिं: Important Notes''',
      '''FEE''': '''शुल्क''',
      '''₹''': '''हिं: ₹''',
      '''Stay focused and\nkeep learning every day.''': '''हिं: Stay focused and\nkeep learning every day.''',
      '''Quick Access''': '''हिं: Quick Access''',
      '''Important Notice''': '''हिं: Important Notice''',
      '''Science Exhibition is scheduled on 24 Jun 2026 at School Auditorium.''': '''Science Exhibition is scheduled on 24 Jun 2026 at स्कूल Auditorium.''',
      '''This is dummy data representing the active status of this module.''': '''हिं: This is dummy data representing the active status of this module.''',
      '''Save Changes''': '''सहेजें Changes''',
      '''A comprehensive school management app for Ecstasy School students and parents.''': '''A comprehensive स्कूल management app for Ecstasy स्कूल students and parents.''',
      '''Active Student''': '''Active छात्र''',
      '''My Info''': '''हिं: My Info''',
      '''Student''': '''छात्र''',
      '''Class 8-A | Roll No: 24''': '''कक्षा 8-A | Roll No: 24''',
      '''Important Notices''': '''हिं: Important Notices''',
      '''3 new notices''': '''हिं: 3 new notices''',
      '''Science Fair tomorrow''': '''हिं: Science Fair tomorrow''',
      '''Exams''': '''हिं: Exams''',
      '''Math Test on Friday''': '''हिं: Math Test on Friday''',
      '''Father Details''': '''हिं: Father Details''',
      '''Mother Details''': '''हिं: Mother Details''',
      '''Edit Profile''': '''संपादित करें Profile''',
      '''Father''': '''हिं: Father''',
      '''Mother''': '''हिं: Mother''',
      '''This feature is currently under development.''': '''हिं: This feature is currently under development.''',
      '''Live Tracking''': '''हिं: Live Tracking''',
      '''Live''': '''हिं: Live''',
      '''View on Map''': '''हिं: View on Map''',
      '''Last updated: Today, 09:41 AM''': '''हिं: Last updated: Today, 09:41 AM''',
      '''Your child has been picked up and is on the way to school.''': '''Your child has been picked up and is on the way to स्कूल.''',
      '''Transport Details''': '''हिं: Transport Details''',
      '''Transport Announcements''': '''हिं: Transport Announcements''',
      '''All Announcements are up to date.''': '''हिं: All Announcements are up to date.''',
      '''Notice''': '''हिं: Notice''',
      '''Please add new classes and sections from the Admin Settings > Study Classes / Sections menu.''': '''Please जोड़ें new classes and sections from the प्रशासक सेटिंग्स > Study Classes / Sections menu.''',
      '''Assign teacher through Admin > Settings > Subjects Mapping''': '''Assign शिक्षक through प्रशासक > सेटिंग्स > Subjects Mapping''',
      '''Manage Subjects''': '''हिं: Manage Subjects''',
      '''Current Subjects:''': '''हिं: Current Subjects:''',
      '''Add''': '''जोड़ें''',
      '''Class Performance Report''': '''कक्षा Performance Report''',
      '''Subjects Summary:''': '''हिं: Subjects Summary:''',
      '''Progress Summary:''': '''हिं: Progress Summary:''',
      '''Downloading report...''': '''हिं: Downloading report...''',
      '''Download PDF''': '''हिं: Download PDF''',
      '''Type your requirement or message for the teacher:''': '''Type your requirement or message for the शिक्षक:''',
      '''Send''': '''हिं: Send''',
      '''Today, Oct 25''': '''हिं: Today, Oct 25''',
      '''Take Attendance''': '''Take उपस्थिति''',
      '''Overview''': '''हिं: Overview''',
      '''Class Details''': '''कक्षा Details''',
      '''Add Class''': '''जोड़ें कक्षा''',
      '''Class / Section''': '''कक्षा / Section''',
      '''Students''': '''हिं: Students''',
      '''Class Teacher''': '''कक्षा शिक्षक''',
      '''Room No.''': '''हिं: Room No.''',
      '''Actions''': '''हिं: Actions''',
      '''All Sections''': '''हिं: All Sections''',
      '''View Details''': '''हिं: View Details''',
      '''Add New Employee''': '''जोड़ें New Employee''',
      '''Status: ''': '''हिं: Status: ''',
      '''Add Employee''': '''जोड़ें Employee''',
      '''Filters clicked''': '''हिं: Filters clicked''',
      '''Employee Name''': '''हिं: Employee Name''',
      '''Employee ID''': '''हिं: Employee ID''',
      '''Role''': '''हिं: Role''',
      '''Department''': '''हिं: Department''',
      '''Action''': '''हिं: Action''',
      '''No employees found''': '''हिं: No employees found''',
      '''Create New Exam''': '''हिं: Create New Exam''',
      '''Create''': '''हिं: Create''',
      '''Performance Report:''': '''हिं: Performance Report:''',
      '''Average Score:''': '''हिं: Average Score:''',
      '''78.5%''': '''हिं: 78.5%''',
      '''Highest Score:''': '''हिं: Highest Score:''',
      '''98.0%''': '''हिं: 98.0%''',
      '''Lowest Score:''': '''हिं: Lowest Score:''',
      '''45.0%''': '''हिं: 45.0%''',
      '''Passing Percentage:''': '''हिं: Passing Percentage:''',
      '''92.3%''': '''हिं: 92.3%''',
      '''Downloading detailed analysis...''': '''हिं: Downloading detailed analysis...''',
      '''Name''': '''हिं: Name''',
      '''Term''': '''हिं: Term''',
      '''New Exam''': '''हिं: New Exam''',
      '''View Report''': '''हिं: View Report''',
      '''This Week''': '''हिं: This Week''',
      '''This Month''': '''हिं: This Month''',
      '''View Timetable >''': '''हिं: View Timetable >''',
      '''Pending Tasks''': '''हिं: Pending Tasks''',
      '''Staff Meeting''': '''हिं: Staff Meeting''',
      '''20 May 2024''': '''हिं: 20 May 2024''',
      '''Monthly staff meeting will be held on 22 May 2024 at 3:00 PM in the conference room. All teachers are requested to attend.''': '''हिं: Monthly staff meeting will be held on 22 May 2024 at 3:00 PM in the conference room. All teachers are requested to attend.''',
      '''New''': '''हिं: New''',
      '''Edit schedule clicked''': '''संपादित करें schedule clicked''',
      '''Remove schedule clicked''': '''हिं: Remove schedule clicked''',
      '''Remove''': '''हिं: Remove''',
      '''Live Session''': '''हिं: Live Session''',
      '''REC''': '''हिं: REC''',
      '''Video is off''': '''हिं: Video is off''',
      '''Join''': '''हिं: Join''',
      '''Quick Portals''': '''हिं: Quick Portals''',
      '''Help Desk''': '''हिं: Help Desk''',
      '''Need assistance? Email support@schoolerp.com or contact the school office (Ext 102).''': '''Need assistance? Email support@schoolerp.com or contact the स्कूल office (Ext 102).''',
      '''A comprehensive school management app for Ecstasy School staff and teachers.''': '''A comprehensive स्कूल management app for Ecstasy स्कूल staff and teachers.''',
      '''Generate New Report''': '''हिं: Generate New Report''',
      '''Generate''': '''हिं: Generate''',
      '''Export Report Data''': '''हिं: Export Report Data''',
      '''Choose export format:''': '''हिं: Choose export format:''',
      '''Microsoft Excel (.xlsx)''': '''हिं: Microsoft Excel (.xlsx)''',
      '''Portable Document Format (.pdf)''': '''हिं: Portable Document Format (.pdf)''',
      '''Comma Separated Values (.csv)''': '''हिं: Comma Separated Values (.csv)''',
      '''Export started... data will download shortly.''': '''हिं: Export started... data will download shortly.''',
      '''Export''': '''हिं: Export''',
      '''Total Students: 538''': '''कुल Students: 538''',
      '''Pass Percentage: 94%''': '''हिं: Pass Percentage: 94%''',
      '''Average Attendance: 92%''': '''Average उपस्थिति: 92%''',
      '''Academic Performance Overview''': '''हिं: Academic Performance Overview''',
      '''View All Reports ->''': '''सभी देखें Reports ->''',
      '''Scheduling feature coming soon...''': '''हिं: Scheduling feature coming soon...''',
      '''Student Name''': '''छात्र Name''',
      '''Presents''': '''हिं: Presents''',
      '''Absents''': '''हिं: Absents''',
      '''Sick Leaves (Used/Total)''': '''Sick Leaves (Used/कुल)''',
      '''Normal Leaves''': '''हिं: Normal Leaves''',
      '''Exam Reports''': '''हिं: Exam Reports''',
      '''Attended''': '''हिं: Attended''',
      '''Passed''': '''हिं: Passed''',
      '''Failed''': '''हिं: Failed''',
      '''Generate Custom Report''': '''हिं: Generate Custom Report''',
      '''Select Criteria''': '''हिं: Select Criteria''',
      '''Date Range''': '''हिं: Date Range''',
      '''Generate Report''': '''हिं: Generate Report''',
      '''Export Options''': '''हिं: Export Options''',
      '''Class Reports''': '''कक्षा Reports''',
      '''Atten. %''': '''हिं: Atten. %''',
      '''Avg. Marks''': '''हिं: Avg. Marks''',
      '''Remarks''': '''हिं: Remarks''',
      '''Gender: ''': '''हिं: Gender: ''',
      '''Filter by Status''': '''हिं: Filter by Status''',
      '''All''': '''हिं: All''',
      '''Active Only''': '''हिं: Active Only''',
      '''Inactive Only''': '''हिं: Inactive Only''',
      '''No siblings found for this class''': '''No siblings found for this कक्षा''',
      '''No ID Card''': '''हिं: No ID Card''',
      '''Import Students''': '''हिं: Import Students''',
      '''Directing to local disk... Select an Excel (.xlsx) or CSV file containing student records.''': '''Directing to local disk... Select an Excel (.xlsx) or CSV file containing छात्र records.''',
      '''Importing data from selected file...''': '''हिं: Importing data from selected file...''',
      '''Select File''': '''हिं: Select File''',
      '''Generating Student List Excel...''': '''Generating छात्र List Excel...''',
      '''Student_List_Class_8A.xlsx downloaded to local storage.''': '''हिं: Student_List_Class_8A.xlsx downloaded to local storage.''',
      '''Create New ID Card''': '''हिं: Create New ID Card''',
      '''Enter student credentials to generate a custom ID card.''': '''Enter छात्र credentials to generate a custom ID card.''',
      '''Student Photo''': '''छात्र Photo''',
      '''Error picking image. Please check permissions.''': '''हिं: Error picking image. Please check permissions.''',
      '''Upload Photo''': '''हिं: Upload Photo''',
      '''Please fill all details''': '''हिं: Please fill all details''',
      '''Edit Student''': '''संपादित करें छात्र''',
      '''Student details updated''': '''छात्र details updated''',
      '''Delete Student''': '''हटाएं छात्र''',
      '''Roll No.''': '''हिं: Roll No.''',
      '''Admission No.''': '''हिं: Admission No.''',
      '''Parent Name''': '''हिं: Parent Name''',
      '''No students found''': '''हिं: No students found''',
      '''Bank Account''': '''हिं: Bank Account''',
      '''Statutory Details''': '''हिं: Statutory Details''',
      '''Statutory Info''': '''हिं: Statutory Info''',
      '''Other Information''': '''हिं: Other Information''',
      '''MAIN''': '''हिं: MAIN''',
      '''Dashboard''': '''डैशबोर्ड''',
      '''Classes''': '''हिं: Classes''',
      '''Reports''': '''हिं: Reports''',
      '''Staff Meeting Tomorrow''': '''हिं: Staff Meeting Tomorrow''',
      '''2''': '''हिं: 2''',
      '''School Calendar''': '''स्कूल Calendar''',
    },
    'Telugu': <String, String>{
      '''Super Administrator''': '''తె: Super Administrator''',
      '''Ecstasy School 1''': '''Ecstasy పాఠశాల 1''',
      '''Ecstasy School 2''': '''Ecstasy పాఠశాల 2''',
      '''Ecstasy School 3''': '''Ecstasy పాఠశాల 3''',
      '''Logout''': '''లాగ్అవుట్''',
      '''Students Overview''': '''తె: Students Overview''',
      '''Students List''': '''విద్యార్థుల జాబితా''',
      '''Register New Student''': '''విద్యార్థి నమోదు''',
      '''Student Promotions''': '''విద్యార్థుల ప్రమోషన్లు''',
      '''Student Siblings''': '''విద్యార్థి తోబుట్టువులు''',
      '''Student ID Cards''': '''విద్యార్థి గుర్తింపు కార్డులు''',
      '''Teachers List''': '''ఉపాధ్యాయుల జాబితా''',
      '''Add New Teacher''': '''కొత్త ఉపాధ్యాయుడిని జోడించండి''',
      '''Configuration''': '''కాన్ఫిగరేషన్''',
      '''Examination''': '''పరీక్ష''',
      '''Communications''': '''కమ్యూనికేషన్స్''',
      '''System Updates''': '''సిస్టమ్ అప్‌డేట్‌లు''',
      '''Video Tutorials''': '''వీడియో ట్యుటోరియల్స్''',
      '''About Us''': '''మా గురించి''',
      '''Empowering Education,\nInspiring Futures''': '''తె: Empowering Education,\nInspiring Futures''',
      '''At Ecstasy School, we are committed to providing quality education through innovation, technology and a student-first approach.''': '''At Ecstasy పాఠశాల, we are committed to providing quality education through innovation, technology and a విద్యార్థి-first approach.''',
      '''Our Mission''': '''తె: Our Mission''',
      '''To deliver a world-class education that nurtures curiosity, builds character and empowers every student to achieve their full potential.''': '''To deliver a world-తరగతి education that nurtures curiosity, builds character and empowers every విద్యార్థి to achieve their full potential.''',
      '''Our Vision''': '''తె: Our Vision''',
      '''To be a global leader in education, recognized for academic excellence, innovation and the holistic development of students.''': '''తె: To be a global leader in education, recognized for academic excellence, innovation and the holistic development of students.''',
      '''Our Core Values''': '''తె: Our Core Values''',
      '''Learn More''': '''Learn మరింత''',
      '''Leadership Team''': '''తె: Leadership Team''',
      '''View All''': '''అన్నీ చూడండి''',
      '''in''': '''తె: in''',
      '''Our History''': '''తె: Our History''',
      '''Read More''': '''Read మరింత''',
      '''“''': '''తె: “''',
      '''Education is the most powerful weapon which you can use to change the world.''': '''తె: Education is the most powerful weapon which you can use to change the world.''',
      '''— Nelson Mandela''': '''తె: — Nelson Mandela''',
      '''Get in Touch''': '''తె: Get in Touch''',
      '''Cancel''': '''రద్దు చేయి''',
      '''Delete Academic Year''': '''తొలగించు Academic Year''',
      '''Delete''': '''తొలగించు''',
      '''Academic Years''': '''తె: Academic Years''',
      '''Add New''': '''జోడించు New''',
      '''Academic Year''': '''తె: Academic Year''',
      '''Is Active''': '''తె: Is Active''',
      '''Items per page:''': '''తె: Items per page:''',
      '''25''': '''తె: 25''',
      '''Current Academic Year''': '''తె: Current Academic Year''',
      '''Save''': '''సేవ్''',
      '''Delete Entry''': '''తొలగించు Entry''',
      '''Entry deleted''': '''తె: Entry deleted''',
      '''10''': '''తె: 10''',
      '''Attendance Analysis''': '''హాజరు Analysis''',
      '''Present''': '''హాజరు''',
      '''Delete Branch''': '''తొలగించు Branch''',
      '''Are you sure you want to delete this branch?''': '''Are you sure you want to తొలగించు this branch?''',
      '''Branch List''': '''తె: Branch List''',
      '''Code''': '''తె: Code''',
      '''Name & Head''': '''తె: Name & Head''',
      '''Contact''': '''తె: Contact''',
      '''No branches found''': '''తె: No branches found''',
      '''Certificate Previews''': '''తె: Certificate Previews''',
      '''ECSTASY INTERNATIONAL SCHOOL''': '''ECSTASY INTERNATIONAL పాఠశాల''',
      '''DATE OF ISSUE''': '''తె: DATE OF ISSUE''',
      '''Certificates Overview''': '''తె: Certificates Overview''',
      '''2,568''': '''తె: 2,568''',
      '''Total''': '''మొత్తం''',
      '''Issued Certificates Log''': '''తె: Issued Certificates Log''',
      '''Starting new chat...''': '''తె: Starting new chat...''',
      '''Start New Chat''': '''తె: Start New Chat''',
      '''Select a chat''': '''తె: Select a chat''',
      '''Delete Mapping''': '''తొలగించు Mapping''',
      '''Are you sure?''': '''తె: Are you sure?''',
      '''Class Subjects Mapping''': '''తరగతి Subjects Mapping''',
      '''Class  /  Subject  /  Teacher''': '''తరగతి  /  Subject  /  ఉపాధ్యాయుడు''',
      '''No mappings added yet.''': '''తె: No mappings added yet.''',
      '''Message Detail''': '''తె: Message Detail''',
      '''Sent''': '''తె: Sent''',
      '''Reply''': '''తె: Reply''',
      '''Forward''': '''తె: Forward''',
      '''Update''': '''నవీకరించు''',
      '''Are you sure you want to remove this configuration entry?''': '''తె: Are you sure you want to remove this configuration entry?''',
      '''Entry deleted.''': '''తె: Entry deleted.''',
      '''Create Event''': '''తె: Create Event''',
      '''Add New Event''': '''జోడించు New Event''',
      '''Event added successfully!''': '''తె: Event added successfully!''',
      '''Save Event''': '''సేవ్ Event''',
      '''Events Calendar''': '''తె: Events Calendar''',
      '''Jun 2026''': '''తె: Jun 2026''',
      '''Upcoming Events''': '''తె: Upcoming Events''',
      '''View All Upcoming Events >''': '''అన్నీ చూడండి Upcoming Events >''',
      '''All Events''': '''తె: All Events''',
      '''Exam Schedule''': '''తె: Exam Schedule''',
      '''View Calendar''': '''తె: View Calendar''',
      '''Performance Overview''': '''తె: Performance Overview''',
      '''75%''': '''తె: 75%''',
      '''Avg Pass''': '''తె: Avg Pass''',
      '''Student Exam Performance Logs''': '''విద్యార్థి Exam Performance Logs''',
      '''Fee Type Collection Breakdown''': '''ఫీజు Type Collection Breakdown''',
      '''Recent Transactions''': '''తె: Recent Transactions''',
      '''Branch''': '''తె: Branch''',
      '''Ecstasy School 1 (ECS001)''': '''Ecstasy పాఠశాల 1 (ECS001)''',
      '''Ecstasy School 2 (ECS002)''': '''Ecstasy పాఠశాల 2 (ECS002)''',
      '''Ecstasy School 3 (ECS003)''': '''Ecstasy పాఠశాల 3 (ECS003)''',
      '''Tuition Fee Collection''': '''Tuition ఫీజు Collection''',
      '''Transport Fee Collection''': '''Transport ఫీజు Collection''',
      '''Fee Due Students''': '''ఫీజు Due Students''',
      '''Term 1''': '''తె: Term 1''',
      '''Term 2''': '''తె: Term 2''',
      '''Term 3''': '''తె: Term 3''',
      '''School Fee Structures (Annual)''': '''పాఠశాల ఫీజు Structures (Annual)''',
      '''School''': '''పాఠశాల''',
      '''Tuition''': '''తె: Tuition''',
      '''Transport''': '''తె: Transport''',
      '''Exam''': '''తె: Exam''',
      '''Please select at least one student to generate invoices.''': '''Please select at least one విద్యార్థి to generate invoices.''',
      '''Term 1 Invoice Batch''': '''తె: Term 1 Invoice Batch''',
      '''Generate Selected''': '''తె: Generate Selected''',
      '''Select All Students''': '''తె: Select All Students''',
      '''All students have generated invoices!''': '''తె: All students have generated invoices!''',
      '''Get Fee Details''': '''Get ఫీజు Details''',
      '''Year''': '''తె: Year''',
      '''Class''': '''తరగతి''',
      '''Fee Type''': '''ఫీజు Type''',
      '''Amount''': '''తె: Amount''',
      '''Delete Fee Type''': '''తొలగించు ఫీజు Type''',
      '''Fee type deleted''': '''ఫీజు type deleted''',
      '''Student Fee Types''': '''విద్యార్థి ఫీజు Types''',
      '''No fee types added yet.''': '''No ఫీజు types added yet.''',
      '''Are you sure you want to delete this entry?''': '''Are you sure you want to తొలగించు this entry?''',
      '''Popular Help Topics''': '''తె: Popular Help Topics''',
      '''Frequently Asked Questions''': '''తె: Frequently Asked Questions''',
      '''My Support Tickets''': '''తె: My Support Tickets''',
      '''Delete Holiday''': '''తొలగించు Holiday''',
      '''Holiday deleted''': '''తె: Holiday deleted''',
      '''Holidays List''': '''తె: Holidays List''',
      '''Date''': '''తె: Date''',
      '''Description''': '''తె: Description''',
      '''No holidays added yet.''': '''తె: No holidays added yet.''',
      '''Room Status Overview''': '''తె: Room Status Overview''',
      '''120''': '''తె: 120''',
      '''Total Rooms''': '''మొత్తం Rooms''',
      '''Hostel Blocks Breakdown''': '''తె: Hostel Blocks Breakdown''',
      '''Hostel Residents Log''': '''తె: Hostel Residents Log''',
      '''ID Card Previews''': '''తె: ID Card Previews''',
      '''Principal Sign''': '''తె: Principal Sign''',
      '''ID Cards Summary''': '''తె: ID Cards Summary''',
      '''1,245''': '''తె: 1,245''',
      '''Recent ID Card Logs''': '''తె: Recent ID Card Logs''',
      '''Would you like to add a new image from gallery or remove the existing one?''': '''Would you like to జోడించు a new image from gallery or remove the existing one?''',
      '''Image removed successfully!''': '''తె: Image removed successfully!''',
      '''Remove Image''': '''తె: Remove Image''',
      '''Image added successfully!''': '''తె: Image added successfully!''',
      '''Add/Update Image''': '''జోడించు/నవీకరించు Image''',
      '''Fee Configurations Requiring Attention''': '''ఫీజు Configurations Requiring Attention''',
      '''The following records have inconsistencies that prevent accurate invoice generation and billing cycles. Please audit and resolve them.''': '''తె: The following records have inconsistencies that prevent accurate invoice generation and billing cycles. Please audit and resolve them.''',
      '''Fix & Reconcile''': '''తె: Fix & Reconcile''',
      '''Total Reconciliation Engine''': '''మొత్తం Reconciliation Engine''',
      '''Reported Total''': '''Reported మొత్తం''',
      '''Calculated Total''': '''Calculated మొత్తం''',
      '''Discrepancy''': '''తె: Discrepancy''',
      '''Audit Explanation:''': '''తె: Audit Explanation:''',
      '''Resolve Adjustment''': '''తె: Resolve Adjustment''',
      '''DATA DISCREPANCIES''': '''తె: DATA DISCREPANCIES''',
      '''Add Book''': '''జోడించు Book''',
      '''Issued Date''': '''తె: Issued Date''',
      '''Due Date''': '''తె: Due Date''',
      '''Send Reminder''': '''తె: Send Reminder''',
      '''Category Distribution''': '''తె: Category Distribution''',
      '''Reports Analytics''': '''తె: Reports Analytics''',
      '''1,256''': '''తె: 1,256''',
      '''Popular Reports Templates''': '''తె: Popular Reports Templates''',
      '''Recent Generated Reports''': '''తె: Recent Generated Reports''',
      '''Export Data''': '''తె: Export Data''',
      '''Close''': '''తె: Close''',
      '''Super Admin Settings''': '''Super అడ్మిన్ సెట్టింగ్‌లు''',
      '''Please select at least one class first.''': '''Please select at least one తరగతి first.''',
      '''Select Students''': '''తె: Select Students''',
      '''Select All''': '''తె: Select All''',
      '''Clear All''': '''తె: Clear All''',
      '''Apply Selection''': '''తె: Apply Selection''',
      '''Please select at least one class.''': '''Please select at least one తరగతి.''',
      '''Please select at least one pending term.''': '''తె: Please select at least one pending term.''',
      '''No students are currently selected to receive SMS.''': '''తె: No students are currently selected to receive SMS.''',
      '''Confirm Send SMS''': '''తె: Confirm Send SMS''',
      '''You are about to send fee due SMS alerts to:''': '''You are about to send ఫీజు due SMS alerts to:''',
      '''This action will dispatch automated SMS alerts to the parents of all selected students.''': '''తె: This action will dispatch automated SMS alerts to the parents of all selected students.''',
      '''Send SMS''': '''తె: Send SMS''',
      '''Sending SMS notifications...''': '''తె: Sending SMS notifications...''',
      '''Success''': '''తె: Success''',
      '''OK''': '''తె: OK''',
      '''Send Fee Due SMS to Selected Students''': '''Send ఫీజు Due SMS to Selected Students''',
      '''Fee pending from''': '''ఫీజు pending from''',
      '''Send to All Students''': '''తె: Send to All Students''',
      '''System Status''': '''తె: System Status''',
      '''All Systems Operational''': '''తె: All Systems Operational''',
      '''Recent Updates Log''': '''తె: Recent Updates Log''',
      '''New Route''': '''తె: New Route''',
      '''Manage Fleet''': '''తె: Manage Fleet''',
      '''Track and manage your school buses in real time.''': '''Track and manage your పాఠశాల buses in real time.''',
      '''Active Fleet & Route Status''': '''తె: Active Fleet & Route Status''',
      '''Assigned Driver''': '''తె: Assigned Driver''',
      '''Stops Covered''': '''తె: Stops Covered''',
      '''Seat Occupancy''': '''తె: Seat Occupancy''',
      '''Experience''': '''తె: Experience''',
      '''Assigned''': '''తె: Assigned''',
      '''Safety Rating''': '''తె: Safety Rating''',
      '''Featured Tutorials''': '''తె: Featured Tutorials''',
      '''Add Branch''': '''జోడించు Branch''',
      '''Add New Branch''': '''జోడించు New Branch''',
      '''Please enter branch name''': '''తె: Please enter branch name''',
      '''Save Branch''': '''సేవ్ Branch''',
      '''Quick Actions''': '''తె: Quick Actions''',
      '''Customize''': '''తె: Customize''',
      '''Customize Quick Actions''': '''తె: Customize Quick Actions''',
      '''Drag to reorder the icons below.''': '''తె: Drag to reorder the icons below.''',
      '''Attendance Overview''': '''హాజరు Overview''',
      '''View attendance report''': '''View హాజరు report''',
      '''Recent Notices''': '''తె: Recent Notices''',
      '''Fee Collection Overview''': '''ఫీజు Collection Overview''',
      '''₹ (Lakh)''': '''తె: ₹ (Lakh)''',
      '''CAMERA VIEWFINDER ACTIVE''': '''తె: CAMERA VIEWFINDER ACTIVE''',
      '''Focus locked. Tap shutter to capture.''': '''తె: Focus locked. Tap shutter to capture.''',
      '''Choose Profile Picture Source''': '''తె: Choose Profile Picture Source''',
      '''Take Photo (Physical Camera)''': '''తె: Take Photo (Physical Camera)''',
      '''Choose from Gallery''': '''తె: Choose from Gallery''',
      '''Simulate Camera Viewfinder''': '''తె: Simulate Camera Viewfinder''',
      '''Interactive mock camera capture''': '''తె: Interactive mock camera capture''',
      '''Remove Photo''': '''తె: Remove Photo''',
      '''Edit Admin Details''': '''సవరించు అడ్మిన్ Details''',
      '''Save Details''': '''సేవ్ Details''',
      '''Account Information''': '''తె: Account Information''',
      '''Security''': '''తె: Security''',
      '''Preferences''': '''తె: Preferences''',
      '''Admin Modules''': '''అడ్మిన్ Modules''',
      '''Edit''': '''సవరించు''',
      '''Two-Factor Authentication''': '''తె: Two-Factor Authentication''',
      '''Add an extra layer of security''': '''జోడించు an extra layer of security''',
      '''Change Password''': '''తె: Change Password''',
      '''Active Sessions''': '''తె: Active Sessions''',
      '''iPhone 13 (Current)''': '''తె: iPhone 13 (Current)''',
      '''Active now''': '''తె: Active now''',
      '''MacBook Pro''': '''తె: MacBook Pro''',
      '''Last active: 2 hours ago''': '''తె: Last active: 2 hours ago''',
      '''Notification Settings''': '''Notification సెట్టింగ్‌లు''',
      '''Push Notifications''': '''తె: Push Notifications''',
      '''Email Alerts''': '''తె: Email Alerts''',
      '''SMS Updates''': '''తె: SMS Updates''',
      '''Select Theme''': '''తె: Select Theme''',
      '''System Default''': '''తె: System Default''',
      '''Light Theme''': '''తె: Light Theme''',
      '''Dark Theme''': '''తె: Dark Theme''',
      '''Region & Time Zone''': '''తె: Region & Time Zone''',
      '''Asia/Kolkata (IST)''': '''తె: Asia/Kolkata (IST)''',
      '''America/New_York (EST)''': '''తె: America/New_York (EST)''',
      '''Europe/London (GMT)''': '''తె: Europe/London (GMT)''',
      '''Sign out from your account''': '''తె: Sign out from your account''',
      '''Are you sure you want to logout?''': '''Are you sure you want to లాగ్అవుట్?''',
      '''Add Student''': '''జోడించు విద్యార్థి''',
      '''More Filters''': '''మరింత Filters''',
      '''Classes Overview (13)''': '''తె: Classes Overview (13)''',
      '''No students found in this class.''': '''No students found in this తరగతి.''',
      '''Add New Student''': '''జోడించు New విద్యార్థి''',
      '''Gender''': '''తె: Gender''',
      '''Male''': '''తె: Male''',
      '''Female''': '''తె: Female''',
      '''Please enter student name''': '''Please enter విద్యార్థి name''',
      '''Save Student''': '''సేవ్ విద్యార్థి''',
      '''No teachers found''': '''తె: No teachers found''',
      '''Add Teacher''': '''జోడించు ఉపాధ్యాయుడు''',
      '''Teacher Profile''': '''ఉపాధ్యాయుడు Profile''',
      '''Please enter teacher name''': '''Please enter ఉపాధ్యాయుడు name''',
      '''Please enter subject''': '''తె: Please enter subject''',
      '''Save Teacher''': '''సేవ్ ఉపాధ్యాయుడు''',
      '''Support Mails''': '''తె: Support Mails''',
      '''12 unread queries''': '''తె: 12 unread queries''',
      '''Active Chats''': '''తె: Active Chats''',
      '''5 unread messages''': '''తె: 5 unread messages''',
      '''Payments Received''': '''తె: Payments Received''',
      '''3 recent transactions''': '''తె: 3 recent transactions''',
      '''Leave Requests''': '''సెలవు Requests''',
      '''2 pending approvals''': '''తె: 2 pending approvals''',
      '''5''': '''తె: 5''',
      '''Hi, Need any help?''': '''తె: Hi, Need any help?''',
      '''AI Assistant''': '''తె: AI Assistant''',
      '''Powered by DeepMind''': '''తె: Powered by DeepMind''',
      '''Simulation Mode Active''': '''తె: Simulation Mode Active''',
      '''Password Recovery''': '''తె: Password Recovery''',
      '''Enter your registered email or mobile number to receive a reset link.''': '''తె: Enter your registered email or mobile number to receive a reset link.''',
      '''Recovery link sent successfully!''': '''తె: Recovery link sent successfully!''',
      '''Send Link''': '''తె: Send Link''',
      '''Choose an account''': '''తె: Choose an account''',
      '''to continue to Ecstasy School ERP''': '''to continue to Ecstasy పాఠశాల ERP''',
      '''A''': '''తె: A''',
      '''admin@ecstasy.edu''': '''అడ్మిన్@ecstasy.edu''',
      '''Admin Account''': '''అడ్మిన్ Account''',
      '''S''': '''తె: S''',
      '''student@ecstasy.edu''': '''విద్యార్థి@ecstasy.edu''',
      '''Student Account''': '''విద్యార్థి Account''',
      '''T''': '''తె: T''',
      '''teacher@ecstasy.edu''': '''ఉపాధ్యాయుడు@ecstasy.edu''',
      '''Teacher Account''': '''ఉపాధ్యాయుడు Account''',
      '''Smart School Management''': '''Smart పాఠశాల Management''',
      '''Welcome Back!''': '''తె: Welcome Back!''',
      '''Login to your account''': '''లాగిన్ to your account''',
      '''User ID''': '''తె: User ID''',
      '''Forgot Password?''': '''తె: Forgot Password?''',
      '''OR''': '''తె: OR''',
      '''Login with Google''': '''లాగిన్ with Google''',
      '''Powered by''': '''తె: Powered by''',
      '''ECSTASY''': '''తె: ECSTASY''',
      '''SCHOOLS ERP''': '''తె: SCHOOLS ERP''',
      '''© 2024 Ecstasy Schools ERP. All rights reserved.''': '''తె: © 2024 Ecstasy Schools ERP. All rights reserved.''',
      '''No events scheduled for this day.''': '''తె: No events scheduled for this day.''',
      '''Downloading Holiday Calendar...''': '''తె: Downloading Holiday Calendar...''',
      '''Download''': '''తె: Download''',
      '''Holiday Name''': '''తె: Holiday Name''',
      '''Day''': '''తె: Day''',
      '''Wednesday, 17 Jun 2026''': '''తె: Wednesday, 17 Jun 2026''',
      '''Timetable''': '''తె: Timetable''',
      '''View Full Timetable''': '''తె: View Full Timetable''',
      '''Period''': '''తె: Period''',
      '''Time''': '''తె: Time''',
      '''Subject''': '''తె: Subject''',
      '''Teacher''': '''ఉపాధ్యాయుడు''',
      '''Room''': '''తె: Room''',
      '''Solve exercise questions from chapter 5.''': '''తె: Solve exercise questions from chapter 5.''',
      '''Pending''': '''తె: Pending''',
      '''Completed''': '''తె: Completed''',
      '''Assignments''': '''తె: Assignments''',
      '''Due Today – Submit before deadline!''': '''తె: Due Today – Submit before deadline!''',
      '''Attendance''': '''హాజరు''',
      '''Attendance Summary''': '''హాజరు Summary''',
      '''Minimum required: 75% | You are above the requirement ✓''': '''తె: Minimum required: 75% | You are above the requirement ✓''',
      '''Monthly Overview''': '''తె: Monthly Overview''',
      '''Subject-wise Attendance''': '''Subject-wise హాజరు''',
      '''June 2026''': '''తె: June 2026''',
      '''Recent History''': '''తె: Recent History''',
      '''Diary''': '''తె: Diary''',
      '''Full Timetable''': '''తె: Full Timetable''',
      '''Break Time''': '''తె: Break Time''',
      '''My Class''': '''My తరగతి''',
      '''Examination Overview''': '''తె: Examination Overview''',
      '''Upcoming Exams''': '''తె: Upcoming Exams''',
      '''View Timetable''': '''తె: View Timetable''',
      '''Recent Exam Results''': '''తె: Recent Exam Results''',
      '''View All Results''': '''అన్నీ చూడండి Results''',
      '''Performance Analysis''': '''తె: Performance Analysis''',
      '''Here is your academic overview based on recent exams:''': '''తె: Here is your academic overview based on recent exams:''',
      '''Great job! Your performance has improved by 4% compared to the last term.''': '''తె: Great job! Your performance has improved by 4% compared to the last term.''',
      '''Term 1 Exam Schedule''': '''తె: Term 1 Exam Schedule''',
      '''Mid Term Academic Report''': '''తె: Mid Term Academic Report''',
      '''Exam Name''': '''తె: Exam Name''',
      '''Duration''': '''తె: Duration''',
      '''Syllabus''': '''తె: Syllabus''',
      '''View All Upcoming Exams''': '''అన్నీ చూడండి Upcoming Exams''',
      '''Marks Obtained''': '''తె: Marks Obtained''',
      '''Total Marks''': '''మొత్తం Marks''',
      '''Percentage''': '''తె: Percentage''',
      '''Grade''': '''తె: Grade''',
      '''Preparing Hall Ticket...''': '''తె: Preparing Hall Ticket...''',
      '''Hall Ticket downloaded successfully!''': '''తె: Hall Ticket downloaded successfully!''',
      '''This tab is under development.''': '''తె: This tab is under development.''',
      '''Total Annual Fees''': '''మొత్తం Annual Fees''',
      '''₹ 45,000''': '''తె: ₹ 45,000''',
      '''Fee Status''': '''ఫీజు Status''',
      '''Downloading Fee Statement...''': '''Downloading ఫీజు Statement...''',
      '''Download Statement''': '''తె: Download Statement''',
      '''Particulars''': '''తె: Particulars''',
      '''Amount (₹)''': '''తె: Amount (₹)''',
      '''Status''': '''తె: Status''',
      '''Total Paid''': '''మొత్తం Paid''',
      '''₹ 20,000''': '''తె: ₹ 20,000''',
      '''Total Due''': '''మొత్తం Due''',
      '''₹ 25,000''': '''తె: ₹ 25,000''',
      '''Redirecting to payment gateway...''': '''తె: Redirecting to payment gateway...''',
      '''Pay Now''': '''తె: Pay Now''',
      '''Paid''': '''తె: Paid''',
      '''Unpaid''': '''తె: Unpaid''',
      '''Recent Payments''': '''తె: Recent Payments''',
      '''Important Notes''': '''తె: Important Notes''',
      '''FEE''': '''ఫీజు''',
      '''₹''': '''తె: ₹''',
      '''Stay focused and\nkeep learning every day.''': '''తె: Stay focused and\nkeep learning every day.''',
      '''Quick Access''': '''తె: Quick Access''',
      '''Important Notice''': '''తె: Important Notice''',
      '''Science Exhibition is scheduled on 24 Jun 2026 at School Auditorium.''': '''Science Exhibition is scheduled on 24 Jun 2026 at పాఠశాల Auditorium.''',
      '''This is dummy data representing the active status of this module.''': '''తె: This is dummy data representing the active status of this module.''',
      '''Save Changes''': '''సేవ్ Changes''',
      '''A comprehensive school management app for Ecstasy School students and parents.''': '''A comprehensive పాఠశాల management app for Ecstasy పాఠశాల students and parents.''',
      '''Active Student''': '''Active విద్యార్థి''',
      '''My Info''': '''తె: My Info''',
      '''Student''': '''విద్యార్థి''',
      '''Class 8-A | Roll No: 24''': '''తరగతి 8-A | Roll No: 24''',
      '''Important Notices''': '''తె: Important Notices''',
      '''3 new notices''': '''తె: 3 new notices''',
      '''Science Fair tomorrow''': '''తె: Science Fair tomorrow''',
      '''Exams''': '''తె: Exams''',
      '''Math Test on Friday''': '''తె: Math Test on Friday''',
      '''Father Details''': '''తె: Father Details''',
      '''Mother Details''': '''తె: Mother Details''',
      '''Edit Profile''': '''సవరించు Profile''',
      '''Father''': '''తె: Father''',
      '''Mother''': '''తె: Mother''',
      '''This feature is currently under development.''': '''తె: This feature is currently under development.''',
      '''Live Tracking''': '''తె: Live Tracking''',
      '''Live''': '''తె: Live''',
      '''View on Map''': '''తె: View on Map''',
      '''Last updated: Today, 09:41 AM''': '''తె: Last updated: Today, 09:41 AM''',
      '''Your child has been picked up and is on the way to school.''': '''Your child has been picked up and is on the way to పాఠశాల.''',
      '''Transport Details''': '''తె: Transport Details''',
      '''Transport Announcements''': '''తె: Transport Announcements''',
      '''All Announcements are up to date.''': '''తె: All Announcements are up to date.''',
      '''Notice''': '''తె: Notice''',
      '''Please add new classes and sections from the Admin Settings > Study Classes / Sections menu.''': '''Please జోడించు new classes and sections from the అడ్మిన్ సెట్టింగ్‌లు > Study Classes / Sections menu.''',
      '''Assign teacher through Admin > Settings > Subjects Mapping''': '''Assign ఉపాధ్యాయుడు through అడ్మిన్ > సెట్టింగ్‌లు > Subjects Mapping''',
      '''Manage Subjects''': '''తె: Manage Subjects''',
      '''Current Subjects:''': '''తె: Current Subjects:''',
      '''Add''': '''జోడించు''',
      '''Class Performance Report''': '''తరగతి Performance Report''',
      '''Subjects Summary:''': '''తె: Subjects Summary:''',
      '''Progress Summary:''': '''తె: Progress Summary:''',
      '''Downloading report...''': '''తె: Downloading report...''',
      '''Download PDF''': '''తె: Download PDF''',
      '''Type your requirement or message for the teacher:''': '''Type your requirement or message for the ఉపాధ్యాయుడు:''',
      '''Send''': '''తె: Send''',
      '''Today, Oct 25''': '''తె: Today, Oct 25''',
      '''Take Attendance''': '''Take హాజరు''',
      '''Overview''': '''తె: Overview''',
      '''Class Details''': '''తరగతి Details''',
      '''Add Class''': '''జోడించు తరగతి''',
      '''Class / Section''': '''తరగతి / Section''',
      '''Students''': '''తె: Students''',
      '''Class Teacher''': '''తరగతి ఉపాధ్యాయుడు''',
      '''Room No.''': '''తె: Room No.''',
      '''Actions''': '''తె: Actions''',
      '''All Sections''': '''తె: All Sections''',
      '''View Details''': '''తె: View Details''',
      '''Add New Employee''': '''జోడించు New Employee''',
      '''Status: ''': '''తె: Status: ''',
      '''Add Employee''': '''జోడించు Employee''',
      '''Filters clicked''': '''తె: Filters clicked''',
      '''Employee Name''': '''తె: Employee Name''',
      '''Employee ID''': '''తె: Employee ID''',
      '''Role''': '''తె: Role''',
      '''Department''': '''తె: Department''',
      '''Action''': '''తె: Action''',
      '''No employees found''': '''తె: No employees found''',
      '''Create New Exam''': '''తె: Create New Exam''',
      '''Create''': '''తె: Create''',
      '''Performance Report:''': '''తె: Performance Report:''',
      '''Average Score:''': '''తె: Average Score:''',
      '''78.5%''': '''తె: 78.5%''',
      '''Highest Score:''': '''తె: Highest Score:''',
      '''98.0%''': '''తె: 98.0%''',
      '''Lowest Score:''': '''తె: Lowest Score:''',
      '''45.0%''': '''తె: 45.0%''',
      '''Passing Percentage:''': '''తె: Passing Percentage:''',
      '''92.3%''': '''తె: 92.3%''',
      '''Downloading detailed analysis...''': '''తె: Downloading detailed analysis...''',
      '''Name''': '''తె: Name''',
      '''Term''': '''తె: Term''',
      '''New Exam''': '''తె: New Exam''',
      '''View Report''': '''తె: View Report''',
      '''This Week''': '''తె: This Week''',
      '''This Month''': '''తె: This Month''',
      '''View Timetable >''': '''తె: View Timetable >''',
      '''Pending Tasks''': '''తె: Pending Tasks''',
      '''Staff Meeting''': '''తె: Staff Meeting''',
      '''20 May 2024''': '''తె: 20 May 2024''',
      '''Monthly staff meeting will be held on 22 May 2024 at 3:00 PM in the conference room. All teachers are requested to attend.''': '''తె: Monthly staff meeting will be held on 22 May 2024 at 3:00 PM in the conference room. All teachers are requested to attend.''',
      '''New''': '''తె: New''',
      '''Edit schedule clicked''': '''సవరించు schedule clicked''',
      '''Remove schedule clicked''': '''తె: Remove schedule clicked''',
      '''Remove''': '''తె: Remove''',
      '''Live Session''': '''తె: Live Session''',
      '''REC''': '''తె: REC''',
      '''Video is off''': '''తె: Video is off''',
      '''Join''': '''తె: Join''',
      '''Quick Portals''': '''తె: Quick Portals''',
      '''Help Desk''': '''తె: Help Desk''',
      '''Need assistance? Email support@schoolerp.com or contact the school office (Ext 102).''': '''Need assistance? Email support@schoolerp.com or contact the పాఠశాల office (Ext 102).''',
      '''A comprehensive school management app for Ecstasy School staff and teachers.''': '''A comprehensive పాఠశాల management app for Ecstasy పాఠశాల staff and teachers.''',
      '''Generate New Report''': '''తె: Generate New Report''',
      '''Generate''': '''తె: Generate''',
      '''Export Report Data''': '''తె: Export Report Data''',
      '''Choose export format:''': '''తె: Choose export format:''',
      '''Microsoft Excel (.xlsx)''': '''తె: Microsoft Excel (.xlsx)''',
      '''Portable Document Format (.pdf)''': '''తె: Portable Document Format (.pdf)''',
      '''Comma Separated Values (.csv)''': '''తె: Comma Separated Values (.csv)''',
      '''Export started... data will download shortly.''': '''తె: Export started... data will download shortly.''',
      '''Export''': '''తె: Export''',
      '''Total Students: 538''': '''మొత్తం Students: 538''',
      '''Pass Percentage: 94%''': '''తె: Pass Percentage: 94%''',
      '''Average Attendance: 92%''': '''Average హాజరు: 92%''',
      '''Academic Performance Overview''': '''తె: Academic Performance Overview''',
      '''View All Reports ->''': '''అన్నీ చూడండి Reports ->''',
      '''Scheduling feature coming soon...''': '''తె: Scheduling feature coming soon...''',
      '''Student Name''': '''విద్యార్థి Name''',
      '''Presents''': '''తె: Presents''',
      '''Absents''': '''తె: Absents''',
      '''Sick Leaves (Used/Total)''': '''Sick Leaves (Used/మొత్తం)''',
      '''Normal Leaves''': '''తె: Normal Leaves''',
      '''Exam Reports''': '''తె: Exam Reports''',
      '''Attended''': '''తె: Attended''',
      '''Passed''': '''తె: Passed''',
      '''Failed''': '''తె: Failed''',
      '''Generate Custom Report''': '''తె: Generate Custom Report''',
      '''Select Criteria''': '''తె: Select Criteria''',
      '''Date Range''': '''తె: Date Range''',
      '''Generate Report''': '''తె: Generate Report''',
      '''Export Options''': '''తె: Export Options''',
      '''Class Reports''': '''తరగతి Reports''',
      '''Atten. %''': '''తె: Atten. %''',
      '''Avg. Marks''': '''తె: Avg. Marks''',
      '''Remarks''': '''తె: Remarks''',
      '''Gender: ''': '''తె: Gender: ''',
      '''Filter by Status''': '''తె: Filter by Status''',
      '''All''': '''తె: All''',
      '''Active Only''': '''తె: Active Only''',
      '''Inactive Only''': '''తె: Inactive Only''',
      '''No siblings found for this class''': '''No siblings found for this తరగతి''',
      '''No ID Card''': '''తె: No ID Card''',
      '''Import Students''': '''తె: Import Students''',
      '''Directing to local disk... Select an Excel (.xlsx) or CSV file containing student records.''': '''Directing to local disk... Select an Excel (.xlsx) or CSV file containing విద్యార్థి records.''',
      '''Importing data from selected file...''': '''తె: Importing data from selected file...''',
      '''Select File''': '''తె: Select File''',
      '''Generating Student List Excel...''': '''Generating విద్యార్థి List Excel...''',
      '''Student_List_Class_8A.xlsx downloaded to local storage.''': '''తె: Student_List_Class_8A.xlsx downloaded to local storage.''',
      '''Create New ID Card''': '''తె: Create New ID Card''',
      '''Enter student credentials to generate a custom ID card.''': '''Enter విద్యార్థి credentials to generate a custom ID card.''',
      '''Student Photo''': '''విద్యార్థి Photo''',
      '''Error picking image. Please check permissions.''': '''తె: Error picking image. Please check permissions.''',
      '''Upload Photo''': '''తె: Upload Photo''',
      '''Please fill all details''': '''తె: Please fill all details''',
      '''Edit Student''': '''సవరించు విద్యార్థి''',
      '''Student details updated''': '''విద్యార్థి details updated''',
      '''Delete Student''': '''తొలగించు విద్యార్థి''',
      '''Roll No.''': '''తె: Roll No.''',
      '''Admission No.''': '''తె: Admission No.''',
      '''Parent Name''': '''తె: Parent Name''',
      '''No students found''': '''తె: No students found''',
      '''Bank Account''': '''తె: Bank Account''',
      '''Statutory Details''': '''తె: Statutory Details''',
      '''Statutory Info''': '''తె: Statutory Info''',
      '''Other Information''': '''తె: Other Information''',
      '''MAIN''': '''తె: MAIN''',
      '''Dashboard''': '''డాష్‌బోర్డ్''',
      '''Classes''': '''తె: Classes''',
      '''Reports''': '''తె: Reports''',
      '''Staff Meeting Tomorrow''': '''తె: Staff Meeting Tomorrow''',
      '''2''': '''తె: 2''',
      '''School Calendar''': '''పాఠశాల Calendar''',
    }
  };

  String tr(String key) {
    if (_currentLanguage == 'English') return key;
    return _translations[_currentLanguage]?[key] ?? key;
  }
}

extension LocalizationExtension on String {
  String get tr {
    return LanguageManager.instance.tr(this);
  }
}
